draft-ietf-tls-rfc8447bis.md
8446bis is in the works, we should refer to it.
=> Refer to draft-ietf-tls-rfc8446bis

draft-ietf-tls-rfc8447bis.md
Reworked intro to make it slightly clearer what changes were motivated when. I also think we should make it easier on IANA and only use the [SHALL/has] intro when we are asking them to make a change as a result of this I-D.
=> Tweaking Intro

draft-ietf-tls-rfc8447bis.md
Clarifying IANA only needs to update references as a result of this section.
=> Session Ticket TLS Extension

draft-ietf-tls-rfc8447bis.md
=> Adding "Recommended" Column

draft-ietf-tls-rfc8447bis.md
Just noting that we'll need to review this based on [draft-ietf-tls-deprecate-obsolete-kex](https://datatracker.ietf.org/doc/draft-ietf-tls-deprecate-obsolete-kex/).
=> Cipher Suites

draft-ietf-tls-rfc8447bis.md
Tweaks for Orphaned Registries. Part 1.
=> Orphaned Registries

draft-ietf-tls-rfc8447bis.md
Tweaks for Supported Groups.
We still need to figure out what to do with curves smaller than 256.
=> TLS Supported Groups

draft-ietf-tls-rfc8447bis.md
changing the DE ref to this document
=> TLS ClientCertificateType Identifiers

draft-ietf-tls-rfc8447bis.md
Ref to 8447bis instead of 8447.
=> NST in Handshake Message Type

draft-ietf-tls-rfc8447bis.md
Just ref updates and making it easier on IANA.
=> TLS CertificateTypes

draft-ietf-tls-rfc8447bis.md
=> Exporter update

draft-ietf-tls-rfc8447bis.md
=> Remove duplicate CS

draft-ietf-tls-rfc8447bis.md
Couple of places the "" were missing around the Y, N, and D values.
=> Adding quotes

draft-ietf-tls-rfc8447bis.md
=> add "Comment" column

draft-ietf-tls-rfc8447bis.md
Need to also refer to this document from the TLS SignatureScheme  registry.
=> Update TLS SignatureScheme registry ref

draft-ietf-tls-rfc8447bis.md
=> support groups note column

draft-ietf-tls-rfc8447bis.md
=> Address s15 ambiguity

draft-ietf-tls-rfc8447bis.md
=> Addressing AD comments

draft-ietf-tls-rfc8447bis.md
If Paul prefers the remove it option for his comments regarding the ranges.  We don't make any changes to them so we could delete them.
=> Addressing decimal

draft-ietf-tls-rfc8447bis.md
A couple of places it was different.
=> Make consistent "Y" to "D" text

draft-ietf-tls-rfc8447bis.md
=> More AD updates

draft-ietf-tls-rfc8447bis.md
=> Fix nits from SecDir Review

draft-ietf-tls-rfc8447bis.md
=> Fix Nits from ArtArt Review

draft-ietf-tls-rfc8447bis.md
=> Address SecDir comments

draft-ietf-tls-rfc8447bis.md
=> Comment not Comments

draft-ietf-tls-rfc8447bis.md
=> New Registration Request Section

draft-ietf-tls-rfc8447bis.md
Consistently adds "Registry" to the headings.
=> Fix Heading Title

draft-ietf-tls-rfc8447bis.md
=> Address Med's Comments
